version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.11.5
    working_directory: ~/repo

jobs:
  setup:
    docker:
      - image: circleci/python:3.11.5
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

  test:
    docker:
      - image: circleci/python:3.11.5
      - image: circleci/postgres:16.3
        environment:
          POSTGRES_USER: $DB_USER
          POSTGRES_DB: $POSTGRES_DB_CHAT
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          CHANNEL_HOST: $CHANNEL_HOST
          CHANNEL_SECRET_KEY: $CHANNEL_SECRET_KEY
          DB_HOST: $DB_HOST
          DB_PORT: $DB_PORT
          DB_USER: $DB_USER
          DEBUG: $DEBUG
          DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE
          POSTGRES_DB_CHAT: $POSTGRES_DB_CHAT
          SECRET_KEY: $SECRET_KEY
      - image: redis
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Wait for Postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for Redis
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run tests
          command: python manage.py test

  deploy:
    docker:
      - image: circleci/python:3.9
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: Deploy to AWS
          environment:
            AWS_EC2_HOST: $AWS_EC2_HOST
            SSH_USER: $SSH_USER
            DOCKER_COMPOSE_FILE: $DOCKER_COMPOSE_FILE
            APP_PATH: $APP_PATH
          command: |
            # Copy files to EC2 instance
            tar -czf app.tar.gz .
            scp app.tar.gz $SSH_USER@$AWS_EC2_HOST:~/app.tar.gz

            # Run remote commands to pull new images and restart the services
            ssh $SSH_USER@$AWS_EC2_HOST << 'EOF'
              docker-compose -f $DOCKER_COMPOSE_FILE down
              tar -xzf app.tar.gz -ะก $APP_PATH --overwrite
              docker-compose -f $DOCKER_COMPOSE_FILE up -d
            EOF

workflows:
  version: 2
  test-deploy:
    jobs:
      - setup
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: deploy/prod
